[package]
name = "logging-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
rmp = "^0.8"
rmp-serde = "1.1.2"
rmpv = "1.0.1"